name: Go Test Coverage
on:
  pull_request:
    branches:
      - main
      - v6
jobs:
  check-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5

      - name: Generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: Check test coverage
        # using vladopajic/go-test-coverage@v2.17.0 below
        uses: vladopajic/go-test-coverage@cc5012c2cfa84542e02b079141958a885861d326
        with:
          config: ./.testcoverage.yml
